### ISSUE TITLE
What key-binding displaying panel are you using?

### ISSUE THREAD

**Issue by vollowx** [towry/nvim#56]
After checking the screenshots without actually trying your configurations, I'm really curious about the helix-like key-binding displaying panel.

**Comment by towry** [comment]
https://github.com/towry/nvim/blob/6d4ea397f3499c79e12a73a7d368a349e9919094/lua/user/plugins/essential.lua#L463

https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-clue.md

I am using this plugin.

**Comment by vollowx** [comment]
Thanks for your quick reply!
